In [1]:
import pandas as pd
from pathlib import Path
import geopandas as gpd
import matplotlib.pyplot as plt
import glob

In [3]:
#Read in the csv file
file = Path("../Data/AK_2000_overall_glacier_covered_area.csv")
df_1 = pd.read_csv(file)
df_1

,RGIId,GLIMSId,BgnDate,EndDate,CenLon,CenLat,O1Region,O2Region,Area,Zmin,...,Lmax,Status,Connect,Form,TermType,Surging,Linkages,Name,GN_area,GN_comp_ye
0,RGI60-01.00002,G213332E63404N,20090703,-9999999,-146.668000,63.404000,1,2,0.558,1713,...,1197,0,0,0,0,9,9,NaN,0.5922,2000
1,RGI60-01.00003,G213920E63376N,20090703,-9999999,-146.080000,63.376000,1,2,1.685,1609,...,2106,0,0,0,0,9,9,NaN,1.8045,2000
2,RGI60-01.00004,G213880E63381N,20090703,-9999999,-146.120000,63.381000,1,2,3.681,1273,...,4175,0,0,0,0,9,9,NaN,3.6765,2000
3,RGI60-01.00005,G212943E63551N,20090703,-9999999,-147.057000,63.551000,1,2,2.573,1494,...,2981,0,0,0,0,9,9,NaN,2.6064,2000
4,RGI60-01.00006,G213756E63571N,20090703,-9999999,-146.244000,63.571000,1,2,10.470,1201,...,10518,0,0,0,0,9,9,NaN,7.7220,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169438,RGI60-01.27102,G225891E58652N,20050811,-9999999,-134.109000,58.652000,1,6,101.741,0,...,44949,0,0,0,1,9,9,Hole-in-the-Wall Glacier,100.1340,2020
169439,RGI60-01.27104,G217822E60805N,20100912,-9999999,-142.178000,60.805000,1,5,0.187,2116,...,441,0,0,0,0,9,9,NaN,0.2106,2020
169440,RGI60-01.27105,G227608E57164N,20040810,-9999999,-132.392000,57.164000,1,6,131.574,507,...,34217,0,0,0,0,9,9,NaN,83.1645,2020
169441,RGI60-01.27108,G216273E60232N,20100910,-9999999,-143.726807,60.231728,1,5,534.228,3,...,72684,0,0,0,0,9,9,NaN,453.3093,2020
169442,RGI60-01.27109,G216916E60532N,20100910,-9999999,-143.084000,60.532000,1,5,0.515,2448,...,389,0,0,0,0,9,9,NaN,0.4653,2020

In [4]:
df_1.shape

(169443, 24)

In [5]:
df_1_copy = df_1.copy()

In [22]:
df_1_copy.columns

Index(['RGIId', 'GLIMSId', 'BgnDate', 'EndDate', 'CenLon', 'CenLat',
       'O1Region', 'O2Region', 'Area', 'Zmin', 'Zmax', 'Zmed', 'Slope',
       'Aspect', 'Lmax', 'Status', 'Connect', 'Form', 'TermType', 'Surging',
       'Linkages', 'Name', 'GN_area', 'GN_comp_ye'],
      dtype='object')

In [6]:
#Read in the shapefiles from the local directory within a for loop
import os
os.environ['SHAPE_RESTORE_SHX'] = 'YES'
data_files = Path("../Resources/Shapefiles")
shapefile_dfs = []
for data_file in data_files.glob("*.shp"):
    df = gpd.read_file(data_file)
    shapefile_dfs.append(df)
concat_shapefile_df = pd.concat(shapefile_dfs, ignore_index=True)

concat_shapefile_df.head(1)

,RGIId,GLIMSId,BgnDate,EndDate,CenLon,CenLat,O1Region,O2Region,Area,Zmin,...,Status,Connect,Form,TermType,Surging,Linkages,Name,GN_area,GN_comp_ye,geometry
0,RGI60-01.00002,G213332E63404N,20090703,-9999999,-146.668,63.404,1,2,0.558,1713,...,0,0,0,0,9,9,None,0.8415,1986,"POLYGON ((365095.000 1512465.000, 365125.000 1..."

In [51]:
#Determine the total number of rows in the concatenated table
concat_shapefile_df.shape

(287327, 25)

DATA EXPLORATION

In [25]:
#Find the columns of the shapefile
concat_shapefile_df.columns

Index(['RGIId', 'GLIMSId', 'BgnDate', 'EndDate', 'CenLon', 'CenLat',
       'O1Region', 'O2Region', 'Area', 'Zmin', 'Zmax', 'Zmed', 'Slope',
       'Aspect', 'Lmax', 'Status', 'Connect', 'Form', 'TermType', 'Surging',
       'Linkages', 'Name', 'GN_area', 'GN_comp_ye', 'geometry'],
      dtype='object')

In [26]:
#Copy the shapefile dataframe
shapefile_df = concat_shapefile_df.copy()
shapefile_df.head()

,RGIId,GLIMSId,BgnDate,EndDate,CenLon,CenLat,O1Region,O2Region,Area,Zmin,...,Status,Connect,Form,TermType,Surging,Linkages,Name,GN_area,GN_comp_ye,geometry
0,RGI60-01.00002,G213332E63404N,20090703,-9999999,-146.668,63.404,1,2,0.558,1713,...,0,0,0,0,9,9,None,0.8415,1986,"POLYGON ((365095.000 1512465.000, 365125.000 1..."
1,RGI60-01.00003,G213920E63376N,20090703,-9999999,-146.080,63.376,1,2,1.685,1609,...,0,0,0,0,9,9,None,1.1295,1986,"POLYGON ((394645.000 1512465.000, 394675.000 1..."
2,RGI60-01.00004,G213880E63381N,20090703,-9999999,-146.120,63.381,1,2,3.681,1273,...,0,0,0,0,9,9,None,1.9764,1986,"MULTIPOLYGON (((392485.000 1512435.000, 392485..."
3,RGI60-01.00005,G212943E63551N,20090703,-9999999,-147.057,63.551,1,2,2.573,1494,...,0,0,0,0,9,9,None,0.1584,1986,"POLYGON ((343285.000 1526025.000, 343315.000 1..."
4,RGI60-01.00006,G213756E63571N,20090703,-9999999,-146.244,63.571,1,2,10.470,1201,...,0,0,0,0,9,9,None,7.2504,1986,"MULTIPOLYGON (((385495.000 1537035.000, 385855..."

In [50]:
# Drop the irrelevant columns
shapefile_df_reduced = shapefile_df[["RGIId","CenLon", "CenLat", "Zmin", "Zmax", "Slope", "Lmax", "Form", "Name", "GN_area", "GN_comp_ye", "geometry"]]
shapefile_df_reduced.head()

,RGIId,CenLon,CenLat,Zmin,Zmax,Slope,Lmax,Form,Name,GN_area,GN_comp_ye,geometry
0,RGI60-01.00002,-146.668,63.404,1713,2144,16.0,1197,0,None,0.8415,1986,"POLYGON ((365095.000 1512465.000, 365125.000 1..."
1,RGI60-01.00003,-146.080,63.376,1609,2182,18.0,2106,0,None,1.1295,1986,"POLYGON ((394645.000 1512465.000, 394675.000 1..."
2,RGI60-01.00004,-146.120,63.381,1273,2317,19.0,4175,0,None,1.9764,1986,"MULTIPOLYGON (((392485.000 1512435.000, 392485..."
3,RGI60-01.00005,-147.057,63.551,1494,2317,16.0,2981,0,None,0.1584,1986,"POLYGON ((343285.000 1526025.000, 343315.000 1..."
4,RGI60-01.00006,-146.244,63.571,1201,3547,22.0,10518,0,None,7.2504,1986,"MULTIPOLYGON (((385495.000 1537035.000, 385855..."

In [52]:
#Compute the change in area between 1986 and 2020 for each glacier

area_1986_df = shapefile_df_reduced.loc[shapefile_df_reduced["GN_comp_ye"]== "1986", ["RGIId","GN_area","geometry"]]
area_2020_df = shapefile_df_reduced.loc[shapefile_df_reduced["GN_comp_ye"]== "2020", ["RGIId","GN_area","geometry"]] 

joined_area_df = area_1986_df.merge(area_2020_df, on=['RGIId'], how="left")


renamed_df = joined_area_df.rename(columns={'GN_area_x': "1986_area", "GN_area_y": "2020_area", "geometry_x":"polygons_2000", "geometry_y": "polygons_2020"})

renamed_df

area_change = renamed_df["2020_area"] - renamed_df["1986_area"]

renamed_df["change_in_area"] = area_change

renamed_df

,RGIId,1986_area,polygons_2000,2020_area,polygons_2020,change_in_area
0,RGI60-01.00002,0.8415,"POLYGON ((365095.000 1512465.000, 365125.000 1...",0.5814,"POLYGON ((364705.000 1513755.000, 364735.000 1...",-0.2601
1,RGI60-01.00003,1.1295,"POLYGON ((394645.000 1512465.000, 394675.000 1...",1.3752,"POLYGON ((394285.000 1514265.000, 394315.000 1...",0.2457
2,RGI60-01.00004,1.9764,"MULTIPOLYGON (((392485.000 1512435.000, 392485...",3.1932,"POLYGON ((392725.000 1515195.000, 392815.000 1...",1.2168
3,RGI60-01.00005,0.1584,"POLYGON ((343285.000 1526025.000, 343315.000 1...",2.3913,"POLYGON ((344185.000 1528335.000, 344305.000 1...",2.2329
4,RGI60-01.00006,7.2504,"MULTIPOLYGON (((385495.000 1537035.000, 385855...",9.6390,"MULTIPOLYGON (((386065.000 1537365.000, 386095...",2.3886
...,...,...,...,...,...,...
17262,RGI60-01.27102,106.2540,"MULTIPOLYGON (((1128685.000 1147455.000, 11287...",100.1340,"POLYGON ((1127995.000 1141455.000, 1127965.000...",-6.1200
17263,RGI60-01.27104,0.1296,"POLYGON ((637615.000 1259565.000, 637645.000 1...",0.2106,"POLYGON ((637555.000 1259655.000, 637585.000 1...",0.0810
17264,RGI60-01.27105,110.0025,"MULTIPOLYGON (((1274515.000 996435.000, 127454...",83.1645,"MULTIPOLYGON (((1280035.000 1012875.000, 12800...",-26.8380
17265,RGI60-01.27108,550.4679,"MULTIPOLYGON (((569515.000 1173765.000, 569515...",453.3093,"MULTIPOLYGON (((562015.000 1187745.000, 562075...",-97.1586
17266,RGI60-01.27109,0.7344,"POLYGON ((593725.000 1221705.000, 593755.000 1...",0.4653,"POLYGON ((593815.000 1221345.000, 593935.000 1...",-0.2691

In [53]:
#Compute the total change in area between 1986 and 2020
total_change = renamed_df["change_in_area"].sum()
total_change

-8544.0717

In [55]:
#Determine the number of glaciers that shrank in size between 1986 and 2020
glacier_retreat_no = renamed_df.iloc[:,5][renamed_df.iloc[:,5]<0].count()
glacier_retreat_no

11652

In [61]:
#Determine the number of glaciers that grew in size between 1986 and 2020
glacier_enlarged = renamed_df.iloc[:,5][renamed_df.iloc[:,5] > 0].count()
glacier_enlarged

2116

In [60]:
total_glacier_change_count = renamed_df.iloc[:,5].count()
total_glacier_change_count

13786

In [33]:
# Save the shapefile dataframe to a csv
concat_shapefile_df.to_csv('shapefiles.csv', index=False)